"""Initial database schema - all tables

Revision ID: 17cfd94a4c79
Revises: 
Create Date: 2026-01-20 10:23:05.193435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17cfd94a4c79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('service_tag', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('asset_tag_internal', sa.String(length=100), nullable=True),
    sa.Column('asset_tag_us', sa.String(length=100), nullable=True),
    sa.Column('warranty_expiry', sa.Date(), nullable=True),
    sa.Column('current_status', sa.String(length=50), nullable=False),
    sa.Column('faulty_sub_status', sa.Text(), nullable=True),
    sa.Column('faulty_since_date', sa.Date(), nullable=True),
    sa.Column('last_faulty_update', sa.Date(), nullable=True),
    sa.Column('in_house', sa.Boolean(), nullable=False),
    sa.Column('storage_location', sa.String(length=200), nullable=True),
    sa.Column('box_included', sa.Boolean(), nullable=True),
    sa.Column('intune_compliance', sa.String(length=50), nullable=True),
    sa.Column('intune_last_checked', sa.Date(), nullable=True),
    sa.Column('intune_checked_by', sa.String(length=100), nullable=True),
    sa.Column('currently_in_repair', sa.Boolean(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('service_tag')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_asset_tag_internal'), ['asset_tag_internal'], unique=True)
        batch_op.create_index(batch_op.f('ix_assets_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_current_status'), ['current_status'], unique=False)

    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('max_machines_allowed', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('date_of_hire', sa.Date(), nullable=False),
    sa.Column('employment_status', sa.String(length=20), nullable=False),
    sa.Column('manager', sa.String(length=200), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_full_name'), ['full_name'], unique=False)

    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_tag', sa.String(length=100), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('assignment_type', sa.String(length=20), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=False),
    sa.Column('unassigned_date', sa.Date(), nullable=True),
    sa.Column('hostname', sa.String(length=100), nullable=True),
    sa.Column('hostname_suggested', sa.String(length=100), nullable=True),
    sa.Column('hostname_manual_override', sa.Boolean(), nullable=True),
    sa.Column('ad_description', sa.String(length=500), nullable=True),
    sa.Column('ad_description_manual_override', sa.Boolean(), nullable=True),
    sa.Column('reserved_for_email', sa.String(length=200), nullable=True),
    sa.Column('reserved_hire_date', sa.Date(), nullable=True),
    sa.Column('multiple_assignment_justification', sa.Text(), nullable=True),
    sa.Column('multiple_assignment_approved_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.employee_id'], ),
    sa.ForeignKeyConstraint(['service_tag'], ['assets.service_tag'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname')
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignments_assigned_date'), ['assigned_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_unassigned_date'), ['unassigned_date'], unique=False)

    op.create_table('history_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_tag', sa.String(length=100), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), nullable=False),
    sa.Column('technician', sa.String(length=100), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('ticket_number', sa.String(length=100), nullable=True),
    sa.Column('issue_description', sa.Text(), nullable=True),
    sa.Column('resolution_date', sa.Date(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('scrap_method', sa.String(length=50), nullable=True),
    sa.Column('vendor_name', sa.String(length=200), nullable=True),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=True),
    sa.Column('from_location', sa.String(length=200), nullable=True),
    sa.Column('to_location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('batch_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.employee_id'], ),
    sa.ForeignKeyConstraint(['service_tag'], ['assets.service_tag'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('history_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_history_events_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_history_events_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_history_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_history_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_history_events_service_tag'), ['service_tag'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_history_events_service_tag'))
        batch_op.drop_index(batch_op.f('ix_history_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_history_events_event_date'))
        batch_op.drop_index(batch_op.f('ix_history_events_employee_id'))
        batch_op.drop_index(batch_op.f('ix_history_events_batch_id'))

    op.drop_table('history_events')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignments_unassigned_date'))
        batch_op.drop_index(batch_op.f('ix_assignments_assigned_date'))

    op.drop_table('assignments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_full_name'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_name'))

    op.drop_table('departments')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_current_status'))
        batch_op.drop_index(batch_op.f('ix_assets_brand'))
        batch_op.drop_index(batch_op.f('ix_assets_asset_tag_internal'))

    op.drop_table('assets')
    # ### end Alembic commands ###
